import { Inter } from 'next/font/google'
import './globals.css'
//import bgImage from '../../public/bg.jpg';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div 
          //className="relative h-screen bg-center bg-cover"
          //style={{backgroundImage: `url(${bgImage})`}}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
